/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FramePrincipal.java
 *
 * Created on 16/03/2010, 08:56:42
 */

package portugol.compilador;

import java.util.ArrayList;
import portugol.arvoresintatica.NoPrograma;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import portugol.intermediario.Instrucao;
import portugol.utilitarios.ImpressaoArvoreSintatica;
import portugol.lexico.Lexema;
import portugol.lexico.Token;
import portugol.utilitarios.ImpressaoCodigoTresEnderecos;
//import
/**
 *
 * @author Kennedy
 */
public class FramePrincipal extends javax.swing.JFrame {

    /** Creates new form FramePrincipal */
    public FramePrincipal() {
        initComponents();

        listModel = new DefaultListModel();
        listaTokens.setModel(listModel);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnLexico = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCodigoFonte = new javax.swing.JTextArea();
        btnSintatico = new javax.swing.JButton();
        btnIntermediario = new javax.swing.JButton();
        btnSemantico = new javax.swing.JButton();
        btnCodigoAssembly = new javax.swing.JToggleButton();
        btnLexico1 = new javax.swing.JToggleButton();
        btnLexico2 = new javax.swing.JToggleButton();
        btnLexico3 = new javax.swing.JToggleButton();
        btnLexico4 = new javax.swing.JToggleButton();
        btnLexico5 = new javax.swing.JToggleButton();
        btnLexico6 = new javax.swing.JToggleButton();
        btnLexico7 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaTokens = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Código"));

        btnLexico.setText("Lexico");
        btnLexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLexicoActionPerformed(evt);
            }
        });

        txtCodigoFonte.setColumns(20);
        txtCodigoFonte.setRows(5);
        jScrollPane1.setViewportView(txtCodigoFonte);

        btnSintatico.setText("Sintatico");
        btnSintatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSintaticoActionPerformed(evt);
            }
        });

        btnIntermediario.setText("Intermediario");
        btnIntermediario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntermediarioActionPerformed(evt);
            }
        });

        btnSemantico.setText("Semantico");
        btnSemantico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSemanticoActionPerformed(evt);
            }
        });

        btnCodigoAssembly.setText("Alvo - Assembly");
        btnCodigoAssembly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodigoAssemblyActionPerformed(evt);
            }
        });

        btnLexico1.setText("< Lexemas");
        btnLexico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLexico1ActionPerformed(evt);
            }
        });

        btnLexico2.setText("< Ler/Escrever");
        btnLexico2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLexico2ActionPerformed(evt);
            }
        });

        btnLexico3.setText("< Se...Entao");
        btnLexico3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLexico3ActionPerformed(evt);
            }
        });

        btnLexico4.setText("< Se...Entao...Senao");
        btnLexico4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                btnLexico4ComponentResized(evt);
            }
        });
        btnLexico4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLexico4ActionPerformed(evt);
            }
        });

        btnLexico5.setText("< Se...Entao...Senao Se");
        btnLexico5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                btnLexico5ComponentResized(evt);
            }
        });
        btnLexico5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLexico5ActionPerformed(evt);
            }
        });

        btnLexico6.setText("< Enquanto...Faca");
        btnLexico6.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                btnLexico6ComponentResized(evt);
            }
        });
        btnLexico6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLexico6ActionPerformed(evt);
            }
        });

        btnLexico7.setText("< Enquanto...Faca");
        btnLexico7.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                btnLexico7ComponentResized(evt);
            }
        });
        btnLexico7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLexico7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIntermediario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSintatico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSemantico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLexico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCodigoAssembly, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLexico1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLexico2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLexico3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLexico4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLexico5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLexico6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLexico7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnLexico1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLexico2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLexico3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLexico4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLexico5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLexico6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLexico7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLexico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSintatico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSemantico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIntermediario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCodigoAssembly))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        listaTokens.setName("tokens"); // NOI18N
        jScrollPane2.setViewportView(listaTokens);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLexicoActionPerformed

        TabelaSimbolos tabelaSimbolos = new TabelaSimbolos();
        AnalisadorLexico analisadorLexico = new AnalisadorLexico(tabelaSimbolos);
        listModel.clear();
        tabelaSimbolos.iniciar();

        analisadorLexico.definirCodigo(txtCodigoFonte.getText());
        while (analisadorLexico.temCodigo()){
            Token token = analisadorLexico.obterToken();
            if (token != null){
               String descricao = Lexema.obterNomeToken(token);
               if (!analisadorLexico.obterLexema().equals(""))
                   descricao += " (lexema "+analisadorLexico.obterLexema()+")";
               listModel.addElement(descricao);
            }
        }

    }//GEN-LAST:event_btnLexicoActionPerformed

    private void btnSintaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSintaticoActionPerformed
        TabelaSimbolos tabelaSimbolos = new TabelaSimbolos();
        TratadorErro tratadorErro = new TratadorErro();
        AnalisadorSintatico analisadorSintatico = new AnalisadorSintatico(tabelaSimbolos, tratadorErro);
        NoPrograma programa = analisadorSintatico.executar(txtCodigoFonte.getText());
        listModel.clear();
        ImpressaoArvoreSintatica impressaoArvore = new ImpressaoArvoreSintatica(tabelaSimbolos,listModel);
        impressaoArvore.executar(programa);
        
    }//GEN-LAST:event_btnSintaticoActionPerformed

    private void btnIntermediarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntermediarioActionPerformed
        TabelaSimbolos tabelaSimbolos = new TabelaSimbolos();
        TratadorErro tratadorErro = new TratadorErro();
        Tradutor tradutor = new Tradutor(tabelaSimbolos, tratadorErro);
        try{
            ArrayList<Instrucao> instrucoes = tradutor.executar(txtCodigoFonte.getText());
            listModel.clear();
            ImpressaoCodigoTresEnderecos impressaoCodigo = new ImpressaoCodigoTresEnderecos(listModel);
            impressaoCodigo.executar(instrucoes);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

    }//GEN-LAST:event_btnIntermediarioActionPerformed

    private void btnSemanticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSemanticoActionPerformed
        TabelaSimbolos tabelaSimbolos = new TabelaSimbolos();
        TratadorErro tratadorErro = new TratadorErro();
        AnalisadorSintatico analisadorSintatico = new AnalisadorSintatico(tabelaSimbolos, tratadorErro);
        AnalisadorSemantico analisadorSemantico = new AnalisadorSemantico(tabelaSimbolos, tratadorErro);
        NoPrograma programa = analisadorSintatico.executar(txtCodigoFonte.getText());
        listModel.clear();
        ImpressaoArvoreSintatica impressaoArvore = new ImpressaoArvoreSintatica(tabelaSimbolos,listModel);
        impressaoArvore.executar(programa);
        analisadorSemantico.executar(programa.obterListaComandos());

    }//GEN-LAST:event_btnSemanticoActionPerformed

    private void btnCodigoAssemblyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodigoAssemblyActionPerformed
        TabelaSimbolos tabelaSimbolos = new TabelaSimbolos();
        TratadorErro tratadorErro = new TratadorErro();
        Tradutor tradutor = new Tradutor(tabelaSimbolos, tratadorErro);
        try{
            ArrayList<Instrucao> instrucoes = tradutor.executar(txtCodigoFonte.getText());
            listModel.clear();
            GeradorCodigoAssembly geradorCodigoAssembly = new GeradorCodigoAssembly(tabelaSimbolos, listModel);
            geradorCodigoAssembly.executar(instrucoes);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_btnCodigoAssemblyActionPerformed

    private void btnLexico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLexico1ActionPerformed
       txtCodigoFonte.setText("programa\n"+
                              "inicio\n"+
                              "fim\n"+
                              "se\n"+
                              "entao\n"+
                              "senao\n"+
                              "enquanto\n"+
                              "faca\n"+
                              "de\n"+
                              "ate\n"+
                              "cadeia\n"+
                              "inteiro\n"+
                              "real\n"+
                              "\"cadeia de caracteres\"\n"+
                              ":=\n"+
                              "+\n"+
                              "-\n"+
                              "*\n"+
                              "/\n"+
                              "=\n"+
                              "<>\n"+
                              "<\n"+
                              "<=\n"+
                              ">\n"+
                              ">=\n"+
                              "(\n"+
                              ")\n"+
                              ":\n"+
                              ";\n");
    }//GEN-LAST:event_btnLexico1ActionPerformed

    private void btnLexico2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLexico2ActionPerformed
        txtCodigoFonte.setText("programa lerEscrever\n"+
                               " x : inteiro;\n"+
                               " y : inteiro;\n"+
                               "inicio\n"+
                               "  ler x;\n"+
                               "  ler y;\n"+
                               "  x := x + 1;\n"+
                               "  escrever x;\n"+
                               "  x := x + y;\n"+
                               "  escrever y;\n"+
                               "fim;\n");
    }//GEN-LAST:event_btnLexico2ActionPerformed

    private void btnLexico3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLexico3ActionPerformed
        txtCodigoFonte.setText("programa SeEntao\n"+
                               " x : inteiro;\n"+
                               " y : inteiro;\n"+
                               "inicio\n"+
                               "  ler x;\n"+
                               "  ler y;\n"+
                               "  se (x > y) entao\n"+
                               "    inicio \n"+
                               "      x := x + 1;\n"+
                               "      escrever x;\n"+
                               "      x := x + y;\n"+
                               "      escrever y;\n"+
                               "    fim;\n"+
                               "fim;\n");
    }//GEN-LAST:event_btnLexico3ActionPerformed

    private void btnLexico4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLexico4ActionPerformed
        txtCodigoFonte.setText("programa SeEntaoSenao\n"+
                               " x : inteiro;\n"+
                               " y : inteiro;\n"+
                               "inicio\n"+
                               "  ler x;\n"+
                               "  ler y;\n"+
                               "  se (x > y) entao\n"+
                               "    inicio \n"+
                               "      x := x + 1;\n"+
                               "      escrever x;\n"+
                               "      x := x + y;\n"+
                               "      escrever y;\n"+
                               "    fim\n"+
                               "  senao\n"+
                               "    inicio\n"+
                               "      x := x * Y;\n"+
                               "      escrever x;\n"+
                               "    fim;\n"+
                               "fim;\n");
    }//GEN-LAST:event_btnLexico4ActionPerformed

    private void btnLexico4ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnLexico4ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLexico4ComponentResized

    private void btnLexico5ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnLexico5ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLexico5ComponentResized

    private void btnLexico5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLexico5ActionPerformed
        txtCodigoFonte.setText("programa SeEntaoSenaoSe\n"+
                               " x : inteiro;\n"+
                               " y : inteiro;\n"+
                               "inicio\n"+
                               "  ler x;\n"+
                               "  ler y;\n"+
                               "  se (x > y) entao\n"+
                               "    inicio \n"+
                               "      x := x + 1;\n"+
                               "      escrever x;\n"+
                               "      x := x + y;\n"+
                               "      escrever y;\n"+
                               "    fim\n"+
                               "  senao se (x-1 > y+1) entao\n"+
                               "    inicio\n"+
                               "      x := x * Y;\n"+
                               "      escrever x;\n"+
                               "    fim;\n"+
                               "fim;\n");
    }//GEN-LAST:event_btnLexico5ActionPerformed

    private void btnLexico6ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnLexico6ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLexico6ComponentResized

    private void btnLexico6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLexico6ActionPerformed
        txtCodigoFonte.setText("programa EnquantoFaca\n"+
                               " x : inteiro;\n"+
                               " y : inteiro;\n"+
                               "inicio\n"+
                               "  ler x;\n"+
                               "  y := 0;\n"+
                               "  enquanto (x > 0) faca\n"+
                               "    inicio \n"+
                               "      y := y + 1;\n"+
                               "      escrever y;\n"+
                               "      x := x - 1;\n"+
                               "      escrever x;\n"+
                               "    fim;\n"+
                               "fim;\n");
    }//GEN-LAST:event_btnLexico6ActionPerformed

    private void btnLexico7ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnLexico7ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLexico7ComponentResized

    private void btnLexico7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLexico7ActionPerformed
        txtCodigoFonte.setText("programa DeAte\n"+
                               " x : inteiro;\n"+
                               " y : inteiro;\n"+
                               "inicio\n"+
                               "  ler x;\n"+
                               "  y := 0;\n"+
                               "  de y := 0 ate 100 faca\n"+
                               "    inicio \n"+
                               "      x := x + y * 1;\n"+
                               "      escrever x;\n"+
                               "    fim;\n"+
                               "fim;\n");
    }//GEN-LAST:event_btnLexico7ActionPerformed


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    private DefaultListModel listModel;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCodigoAssembly;
    private javax.swing.JButton btnIntermediario;
    private javax.swing.JToggleButton btnLexico;
    private javax.swing.JToggleButton btnLexico1;
    private javax.swing.JToggleButton btnLexico2;
    private javax.swing.JToggleButton btnLexico3;
    private javax.swing.JToggleButton btnLexico4;
    private javax.swing.JToggleButton btnLexico5;
    private javax.swing.JToggleButton btnLexico6;
    private javax.swing.JToggleButton btnLexico7;
    private javax.swing.JButton btnSemantico;
    private javax.swing.JButton btnSintatico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listaTokens;
    private javax.swing.JTextArea txtCodigoFonte;
    // End of variables declaration//GEN-END:variables

}
